version: '3.3'
services:
  # Database
  database:
    image: mysql:latest
    container_name: database
    volumes:
      - ./db:/var/lib/mysql
      - ./config/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    env_file: 
      - .env
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - blog-network
  # Wordpress
  wordpress:
    depends_on:
      - database
    image: wordpress:php7.4-fpm-alpine
    container_name: wordpress
    restart: always
    user: "root:root"
    env_file: 
      - .env
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}
    volumes:
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./src:/var/www/html
    networks:
      - blog-network
  # Webserver
  caddy:
    image: caddy:alpine
    container_name: webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./config/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - blog-network
  composer:
    image: composer
    container_name: ${APP_NAME}-composer
    working_dir: /var/www/html
    restart: 'no'
    volumes:
      - ./src:/var/www/html:rw,cached
    networks:
      - blog-network
networks:
  blog-network:
    driver: bridge

# version: '3'
# services:
#   nginx:
#     image: nginx:latest
#     container_name: ${APP_NAME}-nginx
#     ports:
#       - '80:80'
#       - '443:443'
#     volumes:
#       - ./src:/var/www/html:rw,cached
#     environment:
#       - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
#       - "DOMAIN=${DOMAIN}"
#     depends_on:
#       - wordpress
#     restart: always

#   mysql:
#     image: mariadb
#     container_name: ${APP_NAME}-mysql
#     command: --lower_case_table_names=2
#     volumes:
#        - './data/db:/var/lib/mysql:delegated'
#        - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
#     environment:
#       - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
#       - MYSQL_DATABASE=${DB_NAME}
#     restart: always
#     ports:
#       - '3306:3306'

#   wordpress:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: ${APP_NAME}-wordpress
#     volumes:
#       - ./src:/var/www/html:rw,cached
#       - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
#     depends_on:
#       - mysql
#     restart: always
    
#   composer:
#     image: composer
#     container_name: ${APP_NAME}-composer
#     working_dir: /var/www/html
#     restart: 'no'
#     volumes:
#       - ./src:/var/www/html:rw,cached
